apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: custom-metrics
data:
  config.yaml: |
    rules:
    - seriesQuery: 'http_requests_total{kubernetes_namespace!="",pod!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(http_requests_total{kubernetes_namespace="{{.Namespace}}",pod="{{.Pod}}"}[5m])) by (pod)'

