apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: shopping-app
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }

        location /metrics {
            proxy_pass http://localhost:8080/metrics;
        }

        location /api/catalog {
            proxy_pass http://catalog-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/cart {
            proxy_pass http://cart-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/orders {
            proxy_pass http://order-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>TopShop - Online Fashion Store</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            .banner {
                background-color: #f8f9fa;
                padding: 40px 0;
                margin-bottom: 30px;
            }
            .product-card {
                margin-bottom: 30px;
                transition: transform 0.3s;
            }
            .product-card:hover {
                transform: translateY(-5px);
                box-shadow: 0 10px 20px rgba(0,0,0,0.1);
            }
            .footer {
                background-color: #343a40;
                color: white;
                padding: 30px 0;
                margin-top: 50px;
            }
            .navbar-brand {
                font-weight: bold;
                font-size: 24px;
            }
            .nav-link {
                font-weight: 500;
            }
            .category-nav {
                background-color: #e9ecef;
                padding: 10px 0;
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">TopShop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">New Arrivals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Sale</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                </ul>
                <div class="d-flex">
                    <button class="btn btn-outline-primary me-2" id="login-btn">Login</button>
                    <button class="btn btn-primary position-relative" id="cart-btn">
                        Cart
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" id="cart-count">
                            0
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </nav>
    
    <div class="category-nav">
        <div class="container">
            <div class="row">
                <div class="col">
                    <ul class="nav justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-category="men">Men</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-category="women">Women</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-category="kids">Kids</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-category="accessories">Accessories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <div class="banner">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1>Summer Collection 2025</h1>
                    <p class="lead">Discover the latest trends in fashion and get -50% off for new arrivals.</p>
                    <button class="btn btn-primary btn-lg">Shop Now</button>
                </div>
                <div class="col-md-6 text-center">
                    <img src="https://via.placeholder.com/500x300" alt="Summer Collection" class="img-fluid rounded">
                </div>
            </div>
        </div>
    </div>
    
    <div class="container">
        <h2 class="text-center mb-4">Featured Products</h2>
        <div class="row" id="products-container">
            <!-- Products will be loaded here via JavaScript -->
        </div>
    </div>
    
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h5>TopShop</h5>
                    <p>Your one-stop fashion destination for the latest trends.</p>
                </div>
                <div class="col-md-3">
                    <h5>Quick Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">Home</a></li>
                        <li><a href="#" class="text-white">Products</a></li>
                        <li><a href="#" class="text-white">About Us</a></li>
                        <li><a href="#" class="text-white">Contact</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>Customer Service</h5>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">FAQ</a></li>
                        <li><a href="#" class="text-white">Shipping</a></li>
                        <li><a href="#" class="text-white">Returns</a></li>
                        <li><a href="#" class="text-white">Privacy Policy</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>Connect With Us</h5>
                    <div class="d-flex">
                        <a href="#" class="text-white me-2">Facebook</a>
                        <a href="#" class="text-white me-2">Twitter</a>
                        <a href="#" class="text-white me-2">Instagram</a>
                    </div>
                </div>
            </div>
            <hr class="bg-white">
            <div class="text-center">
                <p>© 2025 TopShop. All rights reserved.</p>
            </div>
        </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function() {
            // Product data
            const products = [
                { id: 1, name: "Summer T-Shirt", price: 29.99, category: "men", image: "https://via.placeholder.com/300x400" },
                { id: 2, name: "Casual Jeans", price: 49.99, category: "men", image: "https://via.placeholder.com/300x400" },
                { id: 3, name: "Floral Dress", price: 59.99, category: "women", image: "https://via.placeholder.com/300x400" },
                { id: 4, name: "Leather Jacket", price: 99.99, category: "women", image: "https://via.placeholder.com/300x400" },
                { id: 5, name: "Kids Sneakers", price: 39.99, category: "kids", image: "https://via.placeholder.com/300x400" },
                { id: 6, name: "Stylish Watch", price: 79.99, category: "accessories", image: "https://via.placeholder.com/300x400" },
                { id: 7, name: "Designer Bag", price: 129.99, category: "accessories", image: "https://via.placeholder.com/300x400" },
                { id: 8, name: "Sports Shorts", price: 34.99, category: "men", image: "https://via.placeholder.com/300x400" }
            ];
            
            // Display products
            function displayProducts(productsToShow) {
                const container = $('#products-container');
                container.empty();
                
                productsToShow.forEach(product => {
                    container.append(`
                        <div class="col-md-3">
                            <div class="card product-card">
                                <img src="${product.image}" class="card-img-top" alt="${product.name}">
                                <div class="card-body">
                                    <h5 class="card-title">${product.name}</h5>
                                    <p class="card-text">$${product.price.toFixed(2)}</p>
                                    <button class="btn btn-primary add-to-cart" data-product-id="${product.id}">Add to Cart</button>
                                </div>
                            </div>
                        </div>
                    `);
                });
            }
            
            // Initial load
            displayProducts(products);
            
            // Filter by category
            $('.nav-link[data-category]').on('click', function(e) {
                e.preventDefault();
                const category = $(this).data('category');
                const filteredProducts = category === 'all'
                    ? products
                    : products.filter(product => product.category === category);
                displayProducts(filteredProducts);
            });
            
            // Cart management
            let cartItems = [];
            
            // Add to cart
            $(document).on('click', '.add-to-cart', function() {
                const productId = $(this).data('product-id');
                const product = products.find(p => p.id === productId);
                
                if (product) {
                    cartItems.push(product);
                    updateCartCount();
                    
                    // Cart API call
                    $.ajax({
                        url: '/api/cart',
                        type: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({ productId: productId, quantity: 1 }),
                        success: function(response) {
                            console.log('Product added to cart:', response);
                        },
                        error: function(error) {
                            console.error('Error adding product to cart:', error);
                        }
                    });
                }
            });
            
            // Update cart count
            function updateCartCount() {
                $('#cart-count').text(cartItems.length);
            }
            
            // Cart button click
            $('#cart-btn').on('click', function() {
                alert('Cart items: ' + cartItems.map(item => item.name).join(', '));
                
                // Order API call
                if (cartItems.length > 0) {
                    $.ajax({
                        url: '/api/orders',
                        type: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({ items: cartItems }),
                        success: function(response) {
                            console.log('Order created:', response);
                        },
                        error: function(error) {
                            console.error('Error creating order:', error);
                        }
                    });
                }
            });
            
            // Login button click
            $('#login-btn').on('click', function() {
                alert('Login functionality would be here');
            });
            
            // Catalog API call
            $.ajax({
                url: '/api/catalog',
                type: 'GET',
                success: function(response) {
                    console.log('Catalog data retrieved:', response);
                },
                error: function(error) {
                    console.error('Error retrieving catalog data:', error);
                }
            });
        });
    </script>
    </body>
    </html>